### ISSUE TITLE
Lore of Steel not working properly

### ISSUE THREAD

**Issue by aermilin** [DeadwoodJedi/speed-calculator-bug-tracker#1]
**Describe the bug**
Enabling "Lore of Steel" in the calculator will lead to speed being dropped instead of being increased

**To Reproduce**
1. Add High Khatun as a leader
2. Set her up as 176 speed + 3 speed sets
3. Add Seeker
4. Set up him as 176 speed + 1 speed set

Result:
Khatun 196.2 speed
Seeker 195.93 speed

5. Enable Lore of Steel for Seeker

Result:
Khatun 196.2 speed
Seeker 195.78

Expected: I know for sure that my Seeker goes first in such setup. And this behavior that you have in a calc is mathematically impossible.

**Comment by mitchelkuijpers** [comment]
Hi Aermilin,

Thank you for your bug report.

I can understand the confusion but the true speeds are actually correct. Plarium unfortunately uses rounding in their formulas. That is why it goes down or up in certain cases. The value that Plarium is showing is the **rounded** version of a champions speed. 

If you have proof by adding screenshots of your champions with gear, masteries, stats and a video of Seeker going first then we could look at our formula to see if it's actually wrong (But we have tested this very thoroughly, so this will be highly unlikely).

On thing you could quickly check if both of your champions are fully ascended an lvl 60 because if the base speed is wrong that might also explain why Seeker is going first.

Btw, please refrain from saying things like: 

>  And this behavior that you have in a calc is mathematically impossible.

This is simply untrue and not helpful.

**Comment by mitchelkuijpers** [comment]
Will close this unless we get actual proof, since this is the first thing built and proven to be right.

**Comment by aermilin** [comment]
The actual problem is not Seeker going first or Khatun going first. I was just providing you with some additional info.

The problem is here:
Seeker with 176 speed + 1 speed set without Lore of Steel enabled = 195.93 true speed
Seeker with 176 speed + 1 speed set with Lore of Steel enabled  = 195.78 true speed

By acquiring mastery you are not gaining anything. You are even losing some.

Lore of Speed should give 15% of the attributes granted by base attribute sets.
In our case it is 103 SPD base for Seeker. 1 SPD set gives 12% (12.36). Lore of Steel in this case would be 1.854 SPD. Even if it's rounded down, it should give at least 1 SPD.

That's what I meant by saying "mathematically impossible".
In general, anything and everything is mathematically possible ^.^

**Comment by mitchelkuijpers** [comment]
Your total speed is the speed with lore of steel included.

**Comment by morrison-d1** [comment]
Hey @aermilin hope the below clears it up.  I checked and the calculator appears to be accurate.

     176 total speed with 1 speed set and no Lore of Steel = (103 base speed x 1.12 = 115.36 + 61(from gear) = 176.36 true speed)

     176 total speed with 1 speed set and Lore of Steel = (103 base speed x 1.138 = 117.214 + 59 (from gear) = 176.214 true speed)

**Comment by aermilin** [comment]
Now I see. It's a UX problem then, not intuitive that the speed on a card is already affected by the Lore of Steel. Was thinking that the resulting speed with Lore of Steel enabled is a hidden param.

Expect lots of questions about it. I would suggest to adjust the UI and add some question mark icon with the onHover tooltips explaining that Lore of Speed already affects the champion card speed number.

Another way around - approach that was taken by many SWGOH calculators. Anything related to gear calculations they were expecting you to put base_amount, gear_amount, modifiers.

In the case of Raid champion speed it should be base speed, gear speed (yes, extra steps for a person, but zero questions later), sets, Lore of Steel switch.

Another thing that may lower the confusion is to show the breakdown of calculated values when the user turns the switch ON/OFF.
The user will see that these numbers are changing with his actions and understand what's going on. In the case with Seeker that we've discussed, it would be:

Switch OFF:
Gear - 61 Speed
Lore of Speed - 0 Speed

Switch ON:
Gear - 59 Speed
Lore of Speed - 1.854 Speed

Hope this feedback will help you to grow and improve the calc. Wasn't meant to harm anyone's feelings. I may sound a bit harsh, sorry this workday was too long for me :D

**Comment by mitchelkuijpers** [comment]
No worries, no feelings were harmed. We do want to add way more inline help. But we first want to release it and slowly iterate over it. We thought that the label **Total** speed was clear enough but maybe it isn't. We will improve this in future :+1:
