### ISSUE TITLE
Sir Nicholas not displaying unkillable skill

### ISSUE THREAD

**Issue by I-amLoki** [DeadwoodJedi/speed-calculator-bug-tracker#10]
**Describe the bug**
When attempting to add Sir Nicholas to the calculator his A3 does not display the unkillable buff.

**To Reproduce**
1. Add Sir Nicholas to the calculator
2. Add Speed
3. Sir Nicholas appears on the left side but Unkillable buff does not display.

**Expected behavior**
Unkillable buff should be displayed.

**Screenshots**
![SantaUnkillable](https://user-images.githubusercontent.com/77698992/105092466-462a9e80-5a6f-11eb-8dd4-508c9831cfc8.JPG)

**Desktop (please complete the following information):**
 - Win10
 - Chrome
 - Version 87.0.4280.141

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mitchelkuijpers** [comment]
Hey Loki,

Thank you for your bugreport I just fixed Santa.
