### ISSUE TITLE
typo in documentation - Contributors  ​section. Only for pedants

### ISSUE THREAD

**Issue by BaraBeor** [DeadwoodJedi/speed-calculator-bug-tracker#11]
help would be better as helped
 _To the many others who have **help** me, not only with the calculator, but with the website, discord group, YouTube and Twitch along the way, I give a heartfelt thank you for all you've done!_

**Comment by mitchelkuijpers** [comment]
Thank you for getting this to our attention. I relayed this to DeadwoodJedi and he ensured me to fix this ;). So I'll close this issue.
