### ISSUE TITLE
Krisk

### ISSUE THREAD

**Issue by kratos529** [DeadwoodJedi/speed-calculator-bug-tracker#12]
**Describe the bug**
Krisk ally protect in the calculator falls off one turn early. it looks as if it is not taking its own extend buffs into account. 

![Capture](https://user-images.githubusercontent.com/77704827/105109168-d3babe00-5a70-11eb-8644-d297de0b4dcf.JPG)

**Comment by mitchelkuijpers** [comment]
Hi @kratos529 

You are absolutely right, I just checked and we extended the buffs before applying ally-protect. I changed their order and deployed the fix. I am closing this because this should be resolved now.
