### ISSUE TITLE
Lost my team after login out

### ISSUE THREAD

**Issue by kolvirelune** [DeadwoodJedi/speed-calculator-bug-tracker#14]
After loging in with my Twitch account I defined a CB team with speeds.
Then I log out and back in and all was lost, no team, no champion saved at all.

**Comment by mitchelkuijpers** [comment]
You need to actually press the save button and save that url.

**Comment by mitchelkuijpers** [comment]
After logging in you should see this button if you are a twitch tier 2 subscriber: 
![image](https://user-images.githubusercontent.com/621140/105355641-b44b9e80-5bf2-11eb-8cb9-80c18c4825e2.png)

You need to press that to save CB teams.

**Comment by kolvirelune** [comment]
The button did not exist yet as I was level 1 not 2 by that time but there was no reminder that quitting will not save anything.
I suggest to add this reminder at login and/or log out for accounts that cannot save their "work".
cheers

**Comment by mitchelkuijpers** [comment]
Yeah we want to make it way more clear then we do now, cheers!
