### ISSUE TITLE
Save Button

### ISSUE THREAD

**Issue by Dwza** [DeadwoodJedi/speed-calculator-bug-tracker#15]
You talking about a save button in your video... and you can see it in the video as well, but I can't find it in my account, it's missing.

**Comment by mitchelkuijpers** [comment]
Are you a **Twitch, Tier 2** or **Patreon, Calculator Cowboy** subscriber level or higher? If you are not you need to upgrade to one of those. Once you upgaded you need to make sure you relogin for the changes to take effect.

I'll close this now, if you are at the right tier please feel free te send a message here to let me know.
