### ISSUE TITLE
VALKYRIE PASSIVE

### ISSUE THREAD

**Issue by JSun2727** [DeadwoodJedi/speed-calculator-bug-tracker#19]
Is Valkyrie's turn meter increase on her passive included in the calculator?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RoboHoboBobo** [comment]
Since affinity clan bosses are not (yet?) implemented, it's safe to say that Valkyrie's passive is not going to be seen.

**Comment by mitchelkuijpers** [comment]
This is planned for the future but no ETA yet. I'll close this issue now to keep the bug tracker cleaned up.
