### ISSUE TITLE
Speed Aura isn't saved

### ISSUE THREAD

**Issue by alekseysshubin** [DeadwoodJedi/speed-calculator-bug-tracker#2]
REPRO:

- Open https://deadwoodjedi.info/cb/dfb4523cbcf80a34d6857b5c1782f6d9c15a2c98
- Log in to account with Save enabled 
- Observe Speed Aura is 0%
- Set Speed Aura to 24%
- Click Save
- Open the generated link

Expected: Speed Aura is 24%
Actual: Speed Aura is 0%

**Comment by mitchelkuijpers** [comment]
Hi @alekseysshubin,

Thank you for your detailed bug report, I reproduced the bug and fixed it. Here is a link with the speed aura saved :wink: : https://deadwoodjedi.info/cb/11cf9a8a71deb87537862a4686ade6f3e2818949
