### ISSUE TITLE
Athel a3 ability CD issue

### ISSUE THREAD

**Issue by TAFIV1980** [DeadwoodJedi/speed-calculator-bug-tracker#23]
**Describe the bug**
athel's a3 comes up as a 3 turn CD in the calculator, it's a 4 turn CD fully booked

**To Reproduce**
1. select athel
2. look at a3 cooldown
3. compare to game

**Expected behavior**
for a3 cooldown to match game

**Comment by mitchelkuijpers** [comment]
Thank you for letting us know, I just fixed it and it should be live in 2 minutes.

Best regards,
Mitchel
