### ISSUE TITLE
Rowan's Cooldowns

### ISSUE THREAD

**Issue by RoboHoboBobo** [DeadwoodJedi/speed-calculator-bug-tracker#26]
Rowan's cooldowns currently appear in the calculator as:
A2 - 4
A3 - 4

Rowan's A2 is a 3-turn cooldown. (I notice ayumilove has this wrong as well, I suspect this was pre-"40-champion rework")
Rowan's A3 is a 3-turn cooldown when booked.
![image](https://user-images.githubusercontent.com/70552892/106191546-d9df2780-615f-11eb-9edd-e6d19d023659.png)
![image](https://user-images.githubusercontent.com/70552892/106191570-e2376280-615f-11eb-8e8f-41600450cd37.png)

**Comment by mitchelkuijpers** [comment]
Fixed! thanks @RoboHoboBobo
