### ISSUE TITLE
Aothar A3

### ISSUE THREAD

**Issue by Evrez** [DeadwoodJedi/speed-calculator-bug-tracker#27]
Hello,
Didn't see that it was reported:
Aothar right now, on AUTO battle in CB has priority on his A2->A1.
He do not use A3
In calculator, I can't change priority of A3 to lowest (A1 is still lower)

Could you look into it? :)

**Comment by mitchelkuijpers** [comment]
Thank you for the bug report, it should be fixed now. 

I will close the issue now, please don't hesitate to contact me if it doesn't work.

Best regards,
Mitchel
