### ISSUE TITLE
Uugo

### ISSUE THREAD

**Issue by Orkinman** [DeadwoodJedi/speed-calculator-bug-tracker#28]
Uugo currently is showing an active A4 that gets used as an ability in the tool.  What is showing as the A4 seems to be her passive ability and not one that will actually take up a turn.  It appears Uugo should only have A1, A2, and A3.

**Comment by mitchelkuijpers** [comment]
Thank you for the bug report, it should be fixed now. 

I will close the issue now, please don't hesitate to contact me if it doesn't work.

Best regards,
Mitchel
