### ISSUE TITLE
Speed tunes difference between Calculator and Game also abilities in Calculator are displayed wrong when using delays

### ISSUE THREAD

**Issue by trkmed81** [DeadwoodJedi/speed-calculator-bug-tracker#3]
**Describe the bug**
1)Speed tuning for ultra nightmare on calculator shows wrong use of abilities for 4:3 tuning (See Sepulcher Sentinel)
 2) Reproducing the speed-tuning list in the actual game does not work as listed in the Calculator

** 
After reproducing the speed tunes in the game I was expecting that Valk will always go last after turn 8 .
In reality Valk is always first , Kymar is last.
For more reference please see screen shoots:

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/77678302/105045075-2778d780-5a70-11eb-8c79-3904948cc913.PNG)
![Capture2](https://user-images.githubusercontent.com/77678302/105045095-2c3d8b80-5a70-11eb-9434-70d98ca2d0c2.PNG)

Screen Shots of my setup:
![IMG_4215](https://user-images.githubusercontent.com/77678302/105045777-f64cd700-5a70-11eb-925c-4de56187954a.PNG)
![IMG_4216](https://user-images.githubusercontent.com/77678302/105045787-f8169a80-5a70-11eb-836a-7e729023b266.PNG)
![IMG_4217](https://user-images.githubusercontent.com/77678302/105045791-f947c780-5a70-11eb-8e78-845d24755468.PNG)
![IMG_4218](https://user-images.githubusercontent.com/77678302/105045800-fb118b00-5a70-11eb-9aec-ee7aebc508ad.PNG)
![IMG_4219](https://user-images.githubusercontent.com/77678302/105045807-fc42b800-5a70-11eb-96fb-b4960fb504a4.PNG)
![IMG_4220](https://user-images.githubusercontent.com/77678302/105045809-fd73e500-5a70-11eb-8953-87b616af8cef.PNG)
![IMG_4221](https://user-images.githubusercontent.com/77678302/105045816-ff3da880-5a70-11eb-9cee-4068e1fa2d73.PNG)
![IMG_4222](https://user-images.githubusercontent.com/77678302/105045818-006ed580-5a71-11eb-8ee0-abd000d02a48.PNG)
![IMG_4223](https://user-images.githubusercontent.com/77678302/105045824-01a00280-5a71-11eb-8468-2015f41992ce.PNG)
![IMG_4224](https://user-images.githubusercontent.com/77678302/105045829-02d12f80-5a71-11eb-95e4-e8b4358183b9.PNG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser : Brave
 - Version : 1.18

**Smartphone (please complete the following information):**
 - Device: iPhone 11MaxPro
 - OS:  iOS 14.0
 - Browser Safari
 - Version

**Comment by mitchelkuijpers** [comment]
Hi @trkmed81,

Do you by any chance run this on a affinity boss? Because the calculator does not take valk's speedup in account yet..

**Comment by mitchelkuijpers** [comment]
Ah lol I now see it, you used Prince Kymar in the calculator instead of Tyrant and he is resetting the cooldowns... ;) I'll close this issue and mark it as invalid.
