### ISSUE TITLE
Sethallia displaying improper speeds. 

### ISSUE THREAD

**Issue by maverick99183** [DeadwoodJedi/speed-calculator-bug-tracker#32]
**Describe the bug**
I put in the follow speeds. Sethallia at 311, Lord Shazar at 206, Fayne at 277, SteelSkull at 234, SkullCrusher at 256. It shows Seth taking two turns at the start but doesn't. This is supposed to lead to 6 turns for everyone per three rounds.  

**To Reproduce**
I put in the follow speeds. Sethallia at 311, Lord Shazar at 206, Fayne at 277, SteelSkull at 234, SkullCrusher at 256.

**Expected behavior**
 It shows Seth taking two turns at the start but doesn't. This is supposed to lead to 6 turns for everyone per three rounds.  

**Screenshots**
![dj1](https://user-images.githubusercontent.com/21291057/107141984-134f2a00-68fa-11eb-9e5e-364998ef045f.PNG)
![dj1](https://user-images.githubusercontent.com/21291057/107141996-219d4600-68fa-11eb-92ca-5b5d89333bd2.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maverick99183** [comment]
I believe the issue is that her a3 is not providing as much Turn meter boost as the calculator suggests. The image shows her a3 is delayed but I meant to upload the image with her starting with her a3 which gives close to the same results. If she starts with her a3 she doesn't take an extra turn.   Her a2 cast on shazar does.

**Comment by mitchelkuijpers** [comment]
Hi Maverick,

Thank you for your bug report you were absolutely right she got too much turn meter boost, I just fixed it it was always triggering the conditional speed boosts. Could you please let me know if this fixes your issue? Then I can close this issue.

Best regards,
Mitchel

**Comment by maverick99183** [comment]
It's displaying correctly now. Thanks!

**Comment by mitchelkuijpers** [comment]
Awesome i'll close the issue then.
