### ISSUE TITLE
[Drexthar Bloodtwin] Incorrect Base speed. 97 vs 100

### ISSUE THREAD

**Issue by YokaiiSpirit** [DeadwoodJedi/speed-calculator-bug-tracker#33]
Drexthar Bloodtwin have 97 Base speed into calculator but at 10.02.2021 real base speed is 100
and CD A2 after improovment is 3

**Comment by mitchelkuijpers** [comment]
Thank you you are absolutely right, it is fixed and will be live in a few minutes.
