### ISSUE TITLE
Calculated Speed not consistent with in-game experience

### ISSUE THREAD

**Issue by ThegoodmanKO** [DeadwoodJedi/speed-calculator-bug-tracker#34]
**Describe the bug**
I am running a speed tuned team for Nightmare Clan Boss.
Roshcard The Tower - In-Game Speed 230 - Calculated Speed 230 - 2x Speed Sets, no lore of steel
Paragon - In-Game Speed 160 - Calculated Speed 160 - no speed sets, no lore of steel
Kael - In-Game Speed 160 - Calculated Speed 160.15 - 1x Perception Set, no lore of steel
Frozen Banshee - In-Game Speed 160 - Calculated Speed 159.88 - 1x Speed Set, no lore of steel, A2 was not cast
Mausoleum Mage - In-Game Speed 159 - Calculated Speed 159.48 - 1x Speed Set, no lore of steel, A3 was not cast

The calculator shows that Roshcard will go last before every AoE 1 round. In Round 6, this is NOT true. Mausoleum Mage goes last. This is a manual run.

**To Reproduce**
1. Go to the calculator and setup the team mentioned above
2. Run this actual team on Nightmare Clan Boss - Force Affinity
3. Manual until round 6

**Expected behavior**
The expectation is that Roshcard will take the last turn before the Clan Boss before AoE one. This is not the case.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4
 - Browser: Safari

**Additional context**

**Comment by ThegoodmanKO** [comment]
Found the problem.

Mausoleum Mage has a base speed of 97. The calculator has him at 104.

Thanks for all of your hard work!

**Comment by RoboHoboBobo** [comment]
For completeness: Mausoleum Mage has a base speed of 104 when fully ascended, and 97 otherwise.

**Comment by mitchelkuijpers** [comment]
Happy you found the issue yourself @ThegoodmanKO I'll close this issue now then. @RoboHoboBobo Ok no changes needed on our part then.
