### ISSUE TITLE
Sandlashed inconsistent A2 

### ISSUE THREAD

**Issue by Drauku** [DeadwoodJedi/speed-calculator-bug-tracker#36]
**Describe the bug**
When using Sandlashed Survivor, she will not reliably use her A2 even when it is available. The A2 is only used if an opponent has an active buff.

**To Reproduce**
1. Build a Clan Boss team with Sandlashed, and one other champ that removes opponent buffs (Rhazin for me).
2. Click the Auto on/off each turn so the AI is the one choosing the skill.
3. Watch her behavior when CB has a buff, and when he does not, as long as her A2 is available.
4. Lose tune and die from missing buffs.

**Expected behavior**
The calculator should not assume she will always use her A2 when available.

**Screenshots**
If necessary I can create a video, but I did not record this issue occurring.

**Desktop (please complete the following information):**
 - OS: Win10pro
 - Browser: Chrome 
 - Version Version 88.0.4324.150

**Smartphone (please complete the following information):**
 - Device: [Oneplus 6T]
 - OS: [Android 10]
 - Browser Firefox
 - Version 85.1.3

**Additional context**

**Comment by mitchelkuijpers** [comment]
Hi Drauku,

I actually run a Sandlashed myself with a Rhazin and never ran into this issue so I am pretty sceptical tbh. Could you provide a video of where this happens?

**Comment by Drauku** [comment]
Just got power back today, so I'll work on figuring out the video recording. Apologies if it takes a while... Texas electricity is not reliable right now.

**Comment by Drauku** [comment]
This video should show the issue I am having. Note I clicked Auto on once I could see that Rhazin had removed the ATK+ buff from the CB, and Sandlashed had her A2 available for use.

https://user-images.githubusercontent.com/17952866/108273132-c6a8f180-7138-11eb-93b5-062bd9fd60fb.mp4

**Comment by D34dw00dj3d1** [comment]
Thank you for the video proof of this! This has been forwarded to Raid and I'm hopeful for a reply and fix soon!

Issue is now closed, but thank you SO MUCH for reporting this!

-dwj
