### ISSUE TITLE
Grappler Shield Ability

### ISSUE THREAD

**Issue by Konnected03** [DeadwoodJedi/speed-calculator-bug-tracker#37]
**Describe the bug**
In the clan boss calculator It does not show grapplers shield ability in the turns

**To Reproduce**
1. Go to 'Clan boss calculator my team was Kael warmaiden apothecary grappler and Vogoth.'
2. Click on 'select those champions and look at the results grapplers buff does not apear'
3. Scroll down to 'N/A'

**Expected behavior**
Grappler shield buff to display in results of calculator 

**Screenshots**

<blockquote class="imgur-embed-pub" lang="en" data-id="a/GSKHlBe"  ><a href="//imgur.com/a/GSKHlBe">Grappler Buff `Bug</a></blockquote>`

**Desktop (please complete the following information):**
 - OS: [iOS Tablet]
 - 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by mitchelkuijpers** [comment]
Fixed in latest version, thank you for reporting! And sorry to keep you waiting ;)
