### ISSUE TITLE
Archmage Hellmut and Thea the Tombangel missing

### ISSUE THREAD

**Issue by mithrawnundo** [DeadwoodJedi/speed-calculator-bug-tracker#38]
I thin they should be in because they can now be obtained from doom tower.

**Comment by D34dw00dj3d1** [comment]
yes, this should be implemented shortly - it always takes some time to
implement new champions as they have to be coded individually. thanks!
-dwj

**Comment by mitchelkuijpers** [comment]
They should be available now
