### ISSUE TITLE
Clanboss Order calculations are off.

### ISSUE THREAD

**Issue by tablab1** [DeadwoodJedi/speed-calculator-bug-tracker#39]
Doing an Unkillable Nightmare
team setup:
1. Maneater - 241 spd(1spd/1per)
2. Pain Keeper - 220 spd(1spd)
3. Frozen Banshee 178 Spd(1spd/1per
4. Rotos 179spd(1spd)
5. Occult Brawler 114spd(1spd)

Only 1 Delay Maneater A3 delay 1

Turn 0 Order is correct
Turn 1 Calculator says Maneater is first in the run, but actually Occult Brawler goes first.  Throws the rest of the RUNS off.  
Attached is the Image of the setup. No lore of steel on any either.

![nm unkillable order error](https://user-images.githubusercontent.com/79416973/108634289-2ef81b80-7436-11eb-8f13-43a284387c7a.png)

**Comment by mitchelkuijpers** [comment]
Can you give me screenshots of all the champions? I want to see the Masteries and the stats

**Comment by mitchelkuijpers** [comment]
Also make sure you dont have any of the following masteries: Arcane Celerity, Rapid Response, Cycle of Magic, Lasting Gifts, or Cycle of Revenge.

**Comment by tablab1** [comment]
I think you may have found my problem, Ill test soon, Frozen had Cycle of Magic.  I didn’t put any turn manipulation on any champs, didn’t think about the skill resets.

Does the calculator take into consideration Frozen’ s skill 2 turn meter Manipulation though?

**Comment by mitchelkuijpers** [comment]
Banshee does not use that skill against the clan boss ;-)

**Comment by tablab1** [comment]
Well that's interesting, The one one of the masteries you listed to not use was on my banshee, Cycle of Magic, and not sure how that would affect turn order.  But Ill test out with that gone and let you know.  I'm also in the middle of re-gearing my champs as the STUN target is not working at the moment, Most of my champs are 38 - 40k health and I think I need a bigger range, between the stun target I need(occult brawler) and every one else.

its up to you if you want to close this out till I can test through again with different gear.

**Comment by mitchelkuijpers** [comment]
I'll close it then, please go-to the Discord of Deadwood first to ensure you are seeing a bug.
