### ISSUE TITLE
Reliquary Tender Skill usage not Correct

### ISSUE THREAD

**Issue by ozzybourne92** [DeadwoodJedi/speed-calculator-bug-tracker#40]
**Describe the bug**
Reliquary Tender does not use her A2 after stun and before AOE1, but rather holds it to use between AOE1 and AOE2 to cleanse poisons
Unsure if this is an AI issue with Raid instead

RT is 186 speed with no speed sets or LOS, A2 is fully booked
**Screenshots**

<img width="955" alt="Capture1" src="https://user-images.githubusercontent.com/79417815/108634645-c8e1b780-747a-11eb-9b8e-fef8cafc8ec6.PNG">

**Comment by mitchelkuijpers** [comment]
Hi @ozzybourne92 

Thank you for your bugreport. You are right there is video from Brandon which also shows this: https://www.youtube.com/watch?v=RP8Uh93oVoI this is an issue in Raid and not something we will fix. We are only doing skill prioritization and not AI implementations. So please make sure to file a bugreport with Plarium.

**Comment by mitchelkuijpers** [comment]
Btw she might work on affinity clan bosses on auto since they get a debuff after AOE2 and that means they will still have a debuff after the stun.
