### ISSUE TITLE
DUO MANEATER SPEED CALCULATOR BUG FOR BRUTAL CB

### ISSUE THREAD

**Issue by FexFox1017** [DeadwoodJedi/speed-calculator-bug-tracker#41]
**Describe the bug**
After using the Calculator and including the decimal factor I cant seem to make my unkillable team with 2 man eaters and 3 dps champions. I read some forums on here and looked at the notes and at this current time I didnt see anything wrong with what I tried, again sorry in advance if you read this and I wasted your time I dont mean too. my email is available upon request, i did not want to make it public. if you need to contact me for whatever reason or if you feel like using my account for a video might be helpful to your viewers, I am open to hear how this may work.

**To Reproduce**
BRUTAL CB CALCULATOR 
FME: true speed- 220.52 fully booked- 2 peed set
SME: true speed- 214.76 fully booked- 1 speed set
DRACOMORPH: true speed- 176.76- fully booked- 1 speed set
VALKYRIE: true speed- 176.48 fully booked- 1 speed set
ZAVIA: true speed- 168.60 no books at all- 1 speed set

i tried to do my best to replicate the calculator order i did to help you understand what I mean

my goal is to use the speed tune you have on the website for brutal CB to make my team unkillable the whole fight, in this instance the calculator has the ME's using A3 in the same turn with your recommended speeds.

**Expected behavior**
I expected to input the data in the calculator with speed tuned champions, accounting for the decimal factor of speed sets, and the calculator show me what to do on certain turns for champions.

**Screenshots**
Would Love to Pay to help support and also be able to attach screenshots, but as to my experience I find it very hard to pay for an unfinished project, this problem being fixed will confidently convince me to aid you in support. If i did something wrong please let me know and reach out so I may fix myself and help support your channel. I did watch the tutorial today (that you posted in January 2021) and read your messages on the site but this is still the problem Iv come across

**Desktop (please complete the following information):**
ASUS Laptop Vivo Book

**Additional context**
If I did something wrong, I would love to know and even though you've created many videos on your calculator im sure the community would love to see more and more with maybe not end game accounts, specifically Brutal CB unkillable teams. or maybe just more content geared towards your viewers and not necessarly end game players who have their teams built. mostly refering to players who have the right champions but struggle with the gear setups who spend most time grinding CB and dungeons for gear to make it to end game.

Thank you very much for reading this message if you do, we love your content and I am subscribbed on youtube always awaiting more videos from you and your team.

sincerly FexFox of the Fighting 10

**Comment by FexFox1017** [comment]
iv also tried working compositions with 2 man eaters and a painkeeper, I would love to see a guide on that as to where you could make the painkeeper fast enough to have the man eaters in sinc so that the unkillable would never go down, the goal here is to get the turn 50 unkillable using these 4 champs and the 5th being zavia or painkeeper

**Comment by FexFox1017** [comment]
UPDATE: with pain keeper swapped out for Zavia Brutal can be done unkillable with comp if painkeeper is changed to true speed- 214.24, still however the auto after turn 9 doesnt use the skills in the calculator, it must be manual. im still working on this and would appreciate any help from the community.

**Comment by mitchelkuijpers** [comment]
Hi @FexFox1017,

Are you fighting the Void Affinity CB or another Affinity?

**Comment by mitchelkuijpers** [comment]
Also if you are looking for general speed tuning help please join the DeadwoodJedi's Discord: https://discord.gg/xGreJuH I don't have time to give assistance with tuning UK comps.

**Comment by FexFox1017** [comment]
thank you for the discord, and also every time I fight the clan boss on brutal it is only Void Affinity.

**Comment by mitchelkuijpers** [comment]
I am closing this issue then since it does not see like an issue with the calculator
