### ISSUE TITLE
4:3 Unkilable with Santa and Taurus

### ISSUE THREAD

**Issue by ChristianLoupes21** [DeadwoodJedi/speed-calculator-bug-tracker#42]
**Describe the bug**
After turn 13 the order of the DPS (banshee) changes and does not sinc with the simulator. It gets mixed with the cleanser (Doompriest)

**Comment by RoboHoboBobo** [comment]
This is not the place to report your personal issues with tuning your team.  You are welcome to seek guidance on DeadwoodJedi's Discord: https://discord.gg/xGreJuH

There are calculator links on the guide page (the Blue buttons labeled "ULTRA-NIGHTMARE" and "NIGHTMARE") that show the speed tune working as described.
