### ISSUE TITLE
Skullcrushers A2 buffs in not showed at 1st application

### ISSUE THREAD

**Issue by Daenur26** [DeadwoodJedi/speed-calculator-bug-tracker#43]
**Describe the bug**
Calculator shows only green Unkillable buff on Skullcrusher at A2 application. It also should show blue Ally Protection and Counter Attack buffs at all teammates on the same move, but it doesn't. Next moves are shown correctly.

**To Reproduce**
1. Select Skullcrusher 
2. Select any other champion
3. Check 1st column of calc CB moves and verify that buffs are not shown correctly.

**Expected behavior**

**Screenshots**
![bug](https://user-images.githubusercontent.com/79727670/109364487-99c2b000-7897-11eb-8752-fd4e6bbced20.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Win 10
 - Browser Chrome
 - Version 88.0.4324.190

**Comment by mitchelkuijpers** [comment]
Hi @Daenur26 

This is not how the visualizations work, its shows you when a buff is on at the start of the turn of that champion.
