### ISSUE TITLE
I am not seeing turns after putting in information

### ISSUE THREAD

**Issue by Whickedcgamer** [DeadwoodJedi/speed-calculator-bug-tracker#46]
**Describe the bug**

**To Reproduce**
I enter all the info for the champions and nothing is going into the calculator

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mackbook Air
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 88.0.4324.192 

Screenshot https://1drv.ms/u/s!ArLK8WR-EEJChIhJHWiIhUpdZAlzFw?e=oEVfcq

**Comment by mitchelkuijpers** [comment]
You need to fill in speeds for you champions, please use the DeadwoodJedi discord for support.
