### ISSUE TITLE
Drokgul not showing block damage buff in calculator

### ISSUE THREAD

**Issue by dancingfool** [DeadwoodJedi/speed-calculator-bug-tracker#48]
**Describe the bug**
Drokgul does not show his block damage buff in the calculator

**To Reproduce**
1. Go to 'Drokgul Unkillable' comp in unkillable speed tune list 
2. Click on 'view composition' then click 'Ultra-Nightmare' to bring up the team in your wonderful calculator
3. look at buffs and find everyone else is fine and all other drogkul buffs work fine but no block damage buff can be seen
**Expected behavior**
See block damage buff just as tower shows

**Screenshots**
![image](https://user-images.githubusercontent.com/12885447/110232799-d6fcf280-7ed4-11eb-905b-300110bcd17c.png)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome]
Version 88.0.4324.190 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [iPhone SE]
 - OS: [iOS 14.4]
 - Browser [safari]

**Comment by mitchelkuijpers** [comment]
This is intentional since we don't track HP we don't know if any of your allies HP is below 30%.
