### ISSUE TITLE
Countess Lix in Clan Boss Calculator

### ISSUE THREAD

**Issue by LatraviousMayfield** [DeadwoodJedi/speed-calculator-bug-tracker#49]
The bug is that countess lix A3 within the calculator decreases her own cooldown which is not the case. It makes the 5 turn cooldown A3 into a 4 turn cooldown which is not the case. took me 3 CB runs to officially figure out

**To Reproduce**
1. Create a team with countess lix in it
2. Count the number of her turns before she gets it back.

**Expected behavior**
I would've liked it to have noticed that it was taking only 4 turns instead of 5.

**Screenshots**
![image](https://user-images.githubusercontent.com/19998029/110728335-7aeee280-81e2-11eb-961a-357047eb577a.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version current

**Additional context**

**Comment by mitchelkuijpers** [comment]
Thank you for bringing this to our attention, this has been fixed,
