### ISSUE TITLE
Wrong number of moves per champion

### ISSUE THREAD

**Issue by ho0uston** [DeadwoodJedi/speed-calculator-bug-tracker#51]
**Describe the bug**
The calculator shows a wrong sequence of hero moves. I use a Champion with 190 speed at Brutal CB with 160.
Champion moves once before each of the first three CB moves. After the third CB move Champion moves twice.
But the calculator shows that Champion moves twice after the seventh CB move.

**To Reproduce**
1. Go to https://deadwoodjedi.info/cb
2. Choose Brutal CB (160 speed)
3. Add a champion with 190 speed
4. Observe the champion moves twice at turn 7

**Expected behavior**
Champion moves twice at 3d turn in the game

**Screenshots**
<img width="1280" alt="Знімок екрана 2021-03-31 о 00 51 32" src="https://user-images.githubusercontent.com/81655451/113063010-4c4ea100-91bd-11eb-84f4-15e17c20d142.png">

**Desktop (please complete the following information):**
 - OS: mac os big sur
 - Browser chrome
 - Version 89

**Additional context**

**Comment by ho0uston** [comment]
Ok, now I added all the Champions of my pack and now it seems to be right. Bad El Kazar moves twice after a 3d CB turn. But why does it matter? My Champs do not have any skills to manipulate with stroke scale.
Why Kazar 1-on-1 with CB need more time to out-drive CB?

**Comment by mitchelkuijpers** [comment]
You always need to fill in all the champions because **all the speeds of your champions matter** for the turn order. Please go to DeadwoodJedi's discord for help and only create bugs here after you asked questions there.

**Comment by mitchelkuijpers** [comment]
Good idea @ho0uston just added that:

![image](https://user-images.githubusercontent.com/621140/120695135-533eac00-c4ab-11eb-81e0-971d8f20eaae.png)
