### ISSUE TITLE
Valerie's A2 is not increasing buff duration

### ISSUE THREAD

**Issue by RishuGupta4269** [DeadwoodJedi/speed-calculator-bug-tracker#58]
**Describe the bug**
Valerie's A2 is not increasing buff duration

**To Reproduce**
1. Go to https://www.deadwoodjedi.com/speed-tunes-4/New-Budget-Maneater---3-Bosses-only-1-Comp
2. Click on 'Nightmare,
3. Enter valerie instead of painkeeper. Her A2 should increase all buffs at turn 1. But unkillable starts to fall at turn 2. 
4. https://deadwoodjedi.info/cb/03d1c072e03ee9cf2713aea771528761a9374c18

**Expected behavior**
Valerie's A2 must increase duration of all buffs on all allies at turn 2. Making her, hopefully, a viable replacement for painkeeper.
(PS- Valerie is farmable) 

**Screenshots**
![Screenshot (107)](https://user-images.githubusercontent.com/65338878/118353643-e3609400-b584-11eb-811d-022865ceae5f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version  : 90.0.4430.212 (Official Build) (64-bit)

**Comment by mitchelkuijpers** [comment]
Unkillable cannot be extended.
