### ISSUE TITLE
Tyrant A3 does not include increase defense buff

### ISSUE THREAD

**Issue by breynolds83** [DeadwoodJedi/speed-calculator-bug-tracker#6]
**Describe the bug**
When using Tyrant, his A3 is not putting an increase def buff for team buff tracking

**To Reproduce**
Use Tyrant in a comp

**Expected behavior**
When he casts A3, everyone gets a 2 turn increase def buff

**Desktop (please complete the following information):**
 - OS: Chrome
 - Browser Chrome
 - Version 86.0.4240.199

**Comment by mitchelkuijpers** [comment]
Hi @breynolds83 

Thank you for your bugreport, Tyrant should be fixed now
