### ISSUE TITLE
Speed Calculator fail

### ISSUE THREAD

**Issue by cray0003** [DeadwoodJedi/speed-calculator-bug-tracker#61]
**Describe the bug**
![raid-speed-calc-fail](https://user-images.githubusercontent.com/5380754/118692152-25d1dd00-b7e0-11eb-9efb-1df0c7a93148.jpg)

Hello,

At first I'd like to thank you very much for the free access to the great Speed Calculation tool. I'm quite new to this tool, so I may have done something wrong. The point is that I'm trying to tune a team to UN clan boss (void), by filling their correct speed, sets and lore of steel checkbox. It seems that in 3rd turn the sync is lost: after Fayne attack, the Can Boss used his AOE attack (before Maneater and Tower moves) causing all the plan to fail - it should not happen by following the Speed Calculation tool (see image attached). It seems that the Clan boss is faster than expected (idk).

Best Regards,

**Comment by mitchelkuijpers** [comment]
Please go to [DeadwoodJedi's Discord](https://discord.gg/xGreJuH) for help and only create bugs here after you asked questions there. This looks like a configuration error.
