### ISSUE TITLE
Riho Bonespear

### ISSUE THREAD

**Issue by Az0te** [DeadwoodJedi/speed-calculator-bug-tracker#64]
**Describe the bug**
Riho has A1 blocked, A2 A3 A4 have no buffs

**Expected behavior**
A1  3 turns    (name: Absortion)
A2  3 turns    (name: Pressure Points)
A3  3 turns  [Block Debufs] 2 turns   (name:  Perfect Body)
(remove A4)

Thanks

**Comment by mitchelkuijpers** [comment]
Will release a fix for this shortly, A1 is correct but A4 was not marked as a passive. We currently only track buffs and the buffs work for Riho.
