### ISSUE TITLE
Duchess Lilitu - A2 missing Buffs & using A3

### ISSUE THREAD

**Issue by Posduif81** [DeadwoodJedi/speed-calculator-bug-tracker#7]
**Describe the bug**
The buff from Lilitu's A@ is not showing in CB calc.. missing "Block  Debuffs", Inc Atk and Veil... 

She's also using A3 (can only be used to revive)

**Comment by mitchelkuijpers** [comment]
Thank you will look at this. Once this is fixed i'll send you an update.

**Comment by mitchelkuijpers** [comment]
Just fixed Duchess and added perfect veil we were not showing that buff yet. So I'll close this bug now.
