### ISSUE TITLE
Lydia A2 does not include strengthen buff

### ISSUE THREAD

**Issue by breynolds83** [DeadwoodJedi/speed-calculator-bug-tracker#8]
Describe the bug
When using Lydia, her A2 is not putting a strengthen buff for team buff tracking

To Reproduce
Use Lydia in a comp

Expected behavior
When she casts A2, everyone gets a 2 turn strengthen buff

Desktop (please complete the following information):

OS: Chrome
Browser Chrome
Version 86.0.4240.199

**Comment by mitchelkuijpers** [comment]
Hi @breynolds83

Thank you for your bug report it seems we do not show strengthen yet. I marked this as a bug and will send you an update once I added strengthen.

**Comment by mitchelkuijpers** [comment]
Strengthen should now show up for Lydia, so I'll close this issue now.

Best regards,
Mitchel
