### ISSUE TITLE
Rearguard Sergeant - A3 (Ally Protection) not appearing

### ISSUE THREAD

**Issue by veldranz** [DeadwoodJedi/speed-calculator-bug-tracker#9]
**Describe the bug**
Dear Deadwoodjedi,

what an amazing job (layout, database,... all great). It seems the icon for ally protection from the said A3 does not appear on the champion after casting the spell. However it does appear well with other champ's with the same ability (i.e. Skullcrusher is ok)

Kind regards, and tahnks again for this tool 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mitchelkuijpers** [comment]
Hi @veldranz 

Sorry not DeadwoodJedi here but Mitchel :P

Thank you for your bugreport, I just fixed Rearguard.

**Comment by veldranz** [comment]
Great, im gonna fix the set up of new compo,

Kind regards,
Veldranz
________________________________
De : Mitchel Kuijpers <notifications@github.com>
Envoyé : mardi 19 janvier 2021 22:05
À : DeadwoodJedi/speed-calculator-bug-tracker <speed-calculator-bug-tracker@noreply.github.com>
Cc : veldranz <sebebvoyage@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [DeadwoodJedi/speed-calculator-bug-tracker] Rearguard Sergeant - A3 (Ally Protection) not appearing (#9)


Hi @veldranz<https://github.com/veldranz>

Sorry not DeadwoodJedi here but Mitchel :P

Thank you for your bugreport, I just fixed Rearguard.
